### ISSUE TITLE
Objective-C

### ISSUE THREAD

**Issue by lucianocn** [kayako/KayakoMessengeriOS#2]
Hi,
This library works with objective-c?
Has any docs available?

**Comment by codeOfRobin** [comment]
Hey! Docs are available on: https://developer.kayako.com/messenger/ios/installation/
> This library works with objective-c?

There's no native Objective-C integration, but you can make a `.swift` file that actually does all the work (like the example function [at the bottom of this page](https://developer.kayako.com/messenger/ios/usage/)) and call it from your Objective-C classes.

**Comment by codeOfRobin** [comment]
Hey @lucianocn I'm going to move discussion about this to #6 . Rest assured, we're working on a much better experience for Objective-C devs (we also welcome community contributions 😁, so don't hesitate to submit a PR).
